import React, { useState } from 'react';
import { Sparkles, Share2, Download, MessageSquareText, Globe, Check, ExternalLink } from 'lucide-react';
import { CompanyIntelligence } from '../types';

interface HeaderProps {
  currentIntelligence: CompanyIntelligence | null;
  onToggleAdvisor: () => void;
  isAdvisorOpen: boolean;
}

export const Header: React.FC<HeaderProps> = ({
  currentIntelligence,
  onToggleAdvisor,
  isAdvisorOpen,
}) => {
  const [copiedLink, setCopiedLink] = useState(false);

  const handleShareLink = () => {
    if (!currentIntelligence) return;
    const url = new URL(window.location.href);
    url.searchParams.set('domain', currentIntelligence.domain);
    navigator.clipboard.writeText(url.toString());
    setCopiedLink(true);
    setTimeout(() => setCopiedLink(false), 2500);
  };

  const handleExportDossier = () => {
    if (!currentIntelligence) return;

    const markdown = `# HIDDEN BRAINS B2B PROSPECT INTELLIGENCE REPORT
Target Domain: ${currentIntelligence.domain}
Company Name: ${currentIntelligence.companyName}
Industry: ${currentIntelligence.industry}
Scale: ${currentIntelligence.estimatedScale}
Analyzed At: ${new Date(currentIntelligence.analyzedAt).toLocaleString()}
Prepared for: Hidden Brains Sales & BD Team (https://hiddenbrains.com)

---

## 1. COMPANY EXECUTIVE SUMMARY
${currentIntelligence.executiveSummary}

Headquarters: ${currentIntelligence.headquarters}
Target Audience: ${currentIntelligence.targetAudience}

Core Offerings:
${currentIntelligence.coreOfferings.map(o => `- ${o}`).join('\n')}

---

## 2. TECH STACK & MODERN MERN / AI PAIN POINT AUDIT
Modernization Urgency Score: ${currentIntelligence.techStackObservedOrInferred.modernizationUrgencyScore}/100
AI Readiness Index: ${currentIntelligence.techStackObservedOrInferred.aiReadinessScore}/100

Observed/Inferred Stack:
- Frontend: ${currentIntelligence.techStackObservedOrInferred.frontend.join(', ')}
- Backend: ${currentIntelligence.techStackObservedOrInferred.backend.join(', ')}
- Cloud / Infrastructure: ${currentIntelligence.techStackObservedOrInferred.cloudInfra.join(', ')}
- Database: ${currentIntelligence.techStackObservedOrInferred.database.join(', ')}

Identified Technical Vulnerabilities:
${currentIntelligence.painPoints.map(p => `### [${p.severity.toUpperCase()}] ${p.title}
- Risk: ${p.currentRisk}
- Business Impact: ${p.businessImpact}
- Recommended Remedy: ${p.remedy}
`).join('\n')}

---

## 3. LINKEDIN FOOTPRINT & COLLABORATION / RFP SIGNALS
${currentIntelligence.linkedInSignals.map(s => `### [${s.type.replace('_', ' ').toUpperCase()}] ${s.title}
- Summary: ${s.summary}
- Source: ${s.sourceContext}
- Collaboration Angle: ${s.collaborationAngle}
- Key Stakeholders to Target: ${s.keyStakeholders.join(', ')}
`).join('\n')}

---

## 4. HIDDEN BRAINS SERVICE ALIGNMENT (SERVICES SOLD BY US)
${currentIntelligence.serviceMatches.map(m => `### ${m.serviceName} (${m.serviceCategory})
- Solution URL: ${m.hiddenBrainsOfferingUrl}
- Why It Fits: ${m.whyFit}
- Value Proposition: ${m.valueProposition}
- Hidden Brains Proof: ${m.proofOfCapability}
- Scope of Work:
${m.implementationScope.map(i => `  * ${i}`).join('\n')}
`).join('\n')}

---

## 5. OUTREACH ASSETS

### LinkedIn InMail
Subject: ${currentIntelligence.outreach.linkedInInMail.subject}
${currentIntelligence.outreach.linkedInInMail.body}

### Cold Email Cadence
Step 1 Subject: ${currentIntelligence.outreach.coldEmailSequence.step1Subject}
${currentIntelligence.outreach.coldEmailSequence.step1Body}

Step 2 Follow-Up Subject: ${currentIntelligence.outreach.coldEmailSequence.step2Subject}
${currentIntelligence.outreach.coldEmailSequence.step2Body}

### Discovery Questions for Sales Calls:
${currentIntelligence.outreach.discoveryQuestions.map(q => `- ${q}`).join('\n')}

Generated by Hidden Brains Account Intelligence Agent.
`;

    const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `${currentIntelligence.domain}-hiddenbrains-intelligence.md`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <header className="sticky top-0 z-40 border-b border-slate-200 bg-white/95 backdrop-blur-md shadow-xs">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 sm:h-18 flex items-center justify-between">
        {/* Brand & Identity */}
        <div className="flex items-center gap-3">
          <a
            href="https://hiddenbrains.com/"
            target="_blank"
            rel="noreferrer"
            className="flex items-center gap-3 group transition-opacity hover:opacity-90"
            title="Visit Hidden Brains official website"
          >
            <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-blue-600 via-indigo-600 to-cyan-500 p-0.5 shadow-sm flex items-center justify-center">
              <div className="w-full h-full bg-white rounded-[10px] flex items-center justify-center font-bold text-lg text-blue-700 font-display">
                HB
              </div>
            </div>
            <div>
              <div className="flex items-center gap-2">
                <span className="font-display font-bold text-slate-900 tracking-tight text-base sm:text-lg">
                  HIDDEN BRAINS
                </span>
                <span className="text-[10px] font-bold tracking-wider uppercase px-2 py-0.5 rounded-full bg-blue-50 text-blue-700 border border-blue-200">
                  Infotech
                </span>
              </div>
              <p className="text-xs text-slate-500 hidden sm:block font-medium">
                B2B Prospecting & Account Intelligence Agent
              </p>
            </div>
          </a>
        </div>

        {/* Global Action CTAs */}
        <div className="flex items-center gap-2.5">
          {currentIntelligence && (
            <>
              <button
                id="btn-share-team-url"
                onClick={handleShareLink}
                className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold text-slate-700 bg-white hover:bg-slate-50 border border-slate-200 shadow-xs transition-colors"
                title="Copy shareable link for team members"
              >
                {copiedLink ? (
                  <>
                    <Check className="w-3.5 h-3.5 text-emerald-600" />
                    <span className="text-emerald-700">Link Copied!</span>
                  </>
                ) : (
                  <>
                    <Share2 className="w-3.5 h-3.5 text-blue-600" />
                    <span>Share With Team</span>
                  </>
                )}
              </button>

              <button
                id="btn-export-dossier"
                onClick={handleExportDossier}
                className="hidden md:inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold text-slate-700 bg-white hover:bg-slate-50 border border-slate-200 shadow-xs transition-colors"
                title="Export complete intelligence dossier as Markdown"
              >
                <Download className="w-3.5 h-3.5 text-slate-500" />
                <span>Export Dossier</span>
              </button>
            </>
          )}

          <button
            id="btn-toggle-advisor"
            onClick={onToggleAdvisor}
            className={`inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold transition-all shadow-xs ${
              isAdvisorOpen
                ? 'bg-blue-600 text-white shadow-blue-500/20'
                : 'bg-blue-50 text-blue-700 hover:bg-blue-100/80 border border-blue-200'
            }`}
          >
            <Sparkles className="w-3.5 h-3.5 text-blue-600" />
            <span>AI Deal Advisor</span>
          </button>

          <a
            href="https://hiddenbrains.com"
            target="_blank"
            rel="noreferrer"
            className="hidden lg:inline-flex items-center gap-1 text-xs font-medium text-slate-500 hover:text-slate-800 transition-colors pl-2"
          >
            <span>hiddenbrains.com</span>
            <ExternalLink className="w-3 h-3 text-slate-400" />
          </a>
        </div>
      </div>
    </header>
  );
};
